version: '3.8'

services:
  demo-app:
    build: .
    container_name: demo-app
    ports:
      - "8080:8080"
    networks:
      - ci-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - ci-network

networks:
  ci-network:

volumes:
  jenkins_home: