pipeline {
    agent any
    tools {
        maven 'Maven_3.8.1'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/ulisespallares888/Taller-CI-CD.git', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                 dir('ci-taller-demo') {
                sh 'mvn clean package'
                 }
            }
        }
        stage('Test') {
            steps {
                  dir('ci-taller-demo') {
                sh 'mvn test'
                  }
            }
        }

    }
}